require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - ___*/**/*           # '___' prefixed dirs are excluded
    - vendor/bundle/**/*  # avoid Error: RuboCop found unsupported Ruby version 2.1 in `TargetRubyVersion` parameter (in vendor/bundle/ruby/3.0.0/gems/rainbow-3.0.0/.rubocop.yml).
    - test/**/*

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
