require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

# trying to be good  O:)
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

# No, thank you!
Layout:
  Enabled: false

# affect performance
Metrics:
  Enabled: false

# not cool
Style/CommentedKeyword:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/Documentation:
  Enabled: false

# these cops are disabled only in the test files in order to
# allow to copy and paste the failed output for test reconciliation
Style/StringLiterals:
  Enabled: true
  Exclude:
  - test/**/*
Style/HashSyntax:
  Enabled: true
  Exclude:
  - test/**/*
Style/SymbolArray:
  Enabled: true
  Exclude:
  - test/**/*
